language: node_js
node_js:
- '8.9'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
before_script:
- yarn global add firebase-tools
- yarn global add @angular/cli
script:
- yarn build
- yarn sw
after_success:
  - yarn deploy --token "$FIREBASE_TOKEN"
notifications:
  email:
    on_failure: change
    on_success: change
