language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - yarn build

after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"

notifications:
  email:
    on_failure: change
    on_success: change
